<fieldset class="accountInfo">
    <label for="curpass"><?php echo I::CurrentPassword ?></label>
    <input type="password" name="curpass" id="curpass" value=""/>

    <label for="newpass"><?php echo I::NewPassword ?></label>
    <input type="password" name="newpass" id="newpass" value=""/>

    <label for="confirmpass"><?php echo I::ConfirmPassword ?></label>
    <input type="password" name="confirmpass" id="confirmpass" value=""/>
</fieldset>
<fieldset class="accountAction" style="border:none">
    <input class="btn grey cancel" type="button" value="<?php echo I::Cancel ?>" onclick="history.go(-1)">
    <input class="btn" type="submit" name="" value="<?php echo I::ChangePassword ?>">
</fieldset>