<thead>
<tr>
    <th scope="col">
        <img class="icon" style="margin-top:-2px;" src="var/assets/images/history.png">
        <?php echo I::PointOfTime ?>
    </th>
    <th scope="col"><?php echo I::Symbol ?></th>
    <th scope="col"><?php echo I::SecurityName ?></th>
    <th scope="col">
        <div class="icon three-quarter icon-dollar" style="margin-top:-2px;"></div>
        <?php echo I::Price ?>
    </th>
    <th scope="col"><?php echo I::Transaction ?></th>
    <th scope="col"><?php echo I::Amount ?></th>
</tr>
</thead>