<tfoot>
    <tr>
        <td colspan="5" colspan="4" class="u-textAlignLeft">
            <div class="icon three-quarter icon-sigma" style="margin-top:-2px;"></div>
            <?php echo I::Total ?>
        </td>
        <td class="u-textAlignLeft" colspan="3">
            <?php echo $totalShares ?>
        </td>
        <td class="u-textAlignRight">
            <?php echo  number_format($totalPaid, 2) ?>
        </td>
        <td style="text-align:right">
            <?php print number_format($totalValue, 2); ?>
        </td>
    </tr>
</tfoot>