<thead>
<tr>
    <th scope="col"></th>
    <th scope="col"><?php echo I::Diff ?></th>
    <th scope="col"><?php echo I::Symbol ?></th>
    <th scope="col" colspan="2" style="width:0"><?php echo I::Name ?></th>
    <th scope="col"><?php echo I::Shares ?></th>
    <th scope="col"><?php echo I::Purchased ?></th>
    <th scope="col" class="u-textAlignRight">
        <div class="icon three-quarter icon-dollar" style="margin-top:-2px;"></div>
        <?php echo I::Price ?>
    </th>
    <th scope="col" class="u-textAlignRight"><?php echo I::Paid ?></th>
    <th scope="col" class="u-textAlignRight">
        <div class="icon three-quarter icon-sigma" style="margin-top:-2px;"></div>
        <?php echo I::Total ?>
    </th>
</tr>
</thead>