<fieldset class="accountInfo">
    <input id="toggleBuyFilters" class="btn grey u-floatRight" style="width:30px; margin:10px 12px 0 0" type="button" value="" onclick="Trader.Ui.toggleBuyFilters(); document.getElementById('sword').focus()">

    <div id="buyFilters" class="u-bordered" style="height:135px">
        <label for="sword" style="margin:10px 30px 0 0">
            <!-- <img class="icon" style="margin-top:-8px" src="var/assets/images/search.png" />-->
            <div class="icon icon-search"></div>
            <?php echo I::Symbols ?> (<?php echo models\db\Symbol::getAmountSymbols() ?>) <?php echo I::FulltextSearch ?>:
        </label>

        <input type="text" id="sword" name="sword" style="width:266px; float:left; margin-right:20px" value="<?php echo models\db\User::getLastSearch() ?>" />
        <img class="icon clearInput" onclick="$('#sword').val(''); Trader.Symbol.requestSymbolSearch()" src="var/assets/images/times-circle.png" />
        <br/><br/>

        <select onchange="document.getElementById('sword').value = this.value; Trader.Symbol.requestSymbolSearch()" class="u-clearBoth caretDown" style="width:200px; float:left; margin-left:30px">
            <option value="" selected="selected"><?php echo I::Sector ?>: <?php echo I::All ?></option>
            <optgroup label="<?php echo I::DefensiveSectors ?>">
                <option value="consumer staple"><?php echo I::ConsumerStaples ?></option>
                <option value="utilit"><?php echo I::SectorUtilities ?></option>
            </optgroup>
            <optgroup label="<?php echo I::CyclicalSectors ?>">
                <option value="mater"><?php echo I::BasicMaterials ?></option>
                <option value="capital"><?php echo I::CapitalGoods ?></option>
                <option value="communic"><?php echo I::CommunicationServices ?></option>
                <option value="cons cycl"><?php echo I::ConsumerCyclicals ?></option>
                <option value="energy"><?php echo I::SectoryEnergy ?></option>
                <option value="financ"><?php echo I::SectorFinancial ?></option>
                <option value="health"><?php echo I::HealthCare ?></option>
                <option value="tech"><?php echo I::Technology ?></option>
                <option value="transport"><?php echo I::Transportation ?></option>
            </optgroup>
        </select>

        <?php $result = models\db\Exchange::selectAll(); ?>
        <select style="width:320px; float:left; margin-left:30px" class="caretDown">
            <option selected="selected"><?php echo I::Exchange ?>: <?php echo I::All ?></option>
            <?php
                if($result) {
                    /** @noinspection ForeachSourceInspection */
                    foreach ($result as $row) {
            ?>
                <option><?php echo $row['exchange'] . ' - ' . $row['full_name'] ?></option>
            <?php
                    }
                }
            ?>
        </select>
    </div>

    <input class="btn blueBg u-floatRight u-posRel" id="toNextSymbol" style="width:30px; z-index:10; margin:17px 52px -40px 0" onclick="Trader.Symbol.requestQuoteNextListed(); return false" name="" value="" type="button">
    <input class="btn blueBg u-floatRight u-posRel" id="toPrevSymbol" style="width:30px; z-index:10; margin:17px 6px -40px 0" onclick="Trader.Symbol.requestQuotePreviousListed(); return false" name="" value="" type="button">

    <select id="searchResults"></select>

    <div id="results-summary" class="info-appended">
        0 <?php echo I::Symbols ?>
    </div>
</fieldset>
<script type="text/javascript">
    $('#sword').focus();
    Trader.Symbol.initFindSymbolObserver();
</script>