<?php

/** @noinspection UntrustedInclusionInspection */
/** @noinspection PhpIncludeInspection */
require_once 'app/bootstrap.php';

if (empty($_POST['curpass']) && empty($_POST['newpass']) && empty($_POST['confirmpass'])) {
    trigger_error('All fields empty. Fill up the form.', E_USER_ERROR);
}

$postedPasswordHash  = md5($_POST['curpass']);

$new      = $_POST['newpass'];
$confirm  = $_POST['confirmpass'];

// See if New and Confirm password are same!
if ($new !== $confirm) {
    trigger_error('Error: Passwords Mismatch.', E_USER_ERROR);
} else {
    $new = md5($new);
}

// Check if the current password and new password are different
if ($new === $postedPasswordHash) {
    trigger_error('Enter a new, different password for this account', E_USER_ERROR);
}

// Check to see if the current password matches the MD5
if (!models\db\User::isCurrentPasswordHash($postedPasswordHash)) {
    trigger_error('Password mismatch. Enter correct password!', E_USER_ERROR);
}

models\db\User::updatePassword($new);
helpers\Http::redirect('index.php');