<?php

/** @noinspection UntrustedInclusionInspection */
/** @noinspection PhpIncludeInspection */
require_once 'app/bootstrap.php';
models\Auth::restrictAccess();

$result = models\db\Portfolio::selectRows();
$shownSymbolIDs = [];
$title = 'Portfolio'; ?><!DOCTYPE html>
<html>
    <?php include PATH_APP . '/views/partials/head.phtml'; ?>
    <body class="portfolio <?php echo models\CssTheme::getActiveThemeName(true) ?>">
        <?php
            $subNavIcons = ['repeat'];
            $subNav      = ['ajax-refresh-symbols' => I::UpdateRates ];
            require_once PATH_APP . '/views/partials/navbar.phtml';
            echo models\JavaScript::getScriptTag();
        ?>
        <div class="pageWrap">
            <div class="u-center">
                <div id="dataTableWrap">

                    <?php /*require_once PATH_APP . '/views/partials/portfolio-grid.phtml';*/ ?>

                    <table class="sortable" id="dataTable">
                        <?php require_once PATH_APP . '/views/partials/portfolio-thead.phtml'; ?>
                        <tbody><?php
                            $totalValue  = 0.00;
                            $totalShares = 0;
                            $totalPaid   = 0.00;

                            if ((bool)$result) {
                                while ($row = mysqli_fetch_array($result)) {
                                    $shownSymbolIDs []= $row['id_symbol'];

                                    $totalShares += $row['number_of_share'];
                                    $subtotal     = (float)$row['number_of_share'] * $row['price_latest'];
                                    $totalValue  += $subtotal;

                                    $totalPaid += (float)$row['number_of_share'] * $row['price'];

                                    require PATH_APP . '/views/partials/portfolio-row.phtml';
                                }
                            }
                            if ($totalShares === 0) { ?>
                                <tr>
                                    <td colspan="10" style="padding:20px 0 30px 0">
                                        <span style="padding-left:50px">The portfolio contains no shares.</span>
                                    </td>
                                </tr>
                        <?php } ?>
                        </tbody>
                        <?php require_once PATH_APP . '/views/partials/portfolio-tfoot.phtml'; ?>
                    </table>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(document).ready(function() {
                Trader.DataTable.init('portfolio');
                $('#dataTable').floatThead({position: 'fixed', top: 73});

                Trader.Symbol.initQuoteRefreshShown('<?php echo implode(',', array_unique($shownSymbolIDs)); ?>');
                Trader.Grid.initQuoteLinksObserverInGrid();
            });
        </script>
    </body>
</html>